FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY public/env.template.js /usr/share/nginx/html/env.template.js


# CMD ["npm", "run", "dev", "--", "--host"]
CMD sh -c "envsubst < /usr/share/nginx/html/env.template.js> /usr/share/nginx/html/env.js && nginx -g 'daemon off;'"
EXPOSE 5173