FROM golang:1.24.2-alpine AS build


WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o api-golang

FROM alpine:latest

WORKDIR /app
COPY --from=build /app/api-golang .

EXPOSE 8080

CMD ["./api-golang"]
